### PR TITLE
added icons, removed redundant files, moved the menu to the equipment

### PR DESCRIPTION
**Pull request by EntranceJew**

### CODE REVIEW

**Comment by EntranceJew** [comment]
also moved files so the repo could be cloned cleanly into the addons folder

**Comment by Blechkanne** [comment]
hey! i don't see why that's necessary, i like using the addon settings page instead of the huge swep page. The Icon is also barely a different icon, except it has less contrast and the jagged edge is gone. Feel free to add cool new features instead of refactors to the addon though!

**Comment by TimGoll** [comment]
I just want to chime in here to say that the equipment settings menu is designed to have the settings for the equipment. Basically all weapons already do this, as do all roles. So this PR would be an improvement imho, because this is one of the few addons that doesn't follow the TTT2 style

**Comment by EntranceJew** [comment]
image
the icon is pretty different, in this lineup the ameterasu stands out on solid blue background, while two icons i redid for you all slot in

image
in a lineup of server settings, having stuff like "Fan", "Soap", and "Prop Rain" get in the way of actual server-related addons and settings, especially while trying to teach server admins that all settings directly related to a weapon or equipment should be edited from the "Edit Equipment" menu

image
where things can be found quickly and with a photo reference, rather than looking through an unalphabetized list with just words

**Comment by Blechkanne** [comment]
> I just want to chime in here to say that the equipment settings menu is designed to have the settings for the equipment. Basically all weapons already do this, as do all roles. So this PR would be an improvement imho, because this is one of the few addons that doesn't follow the TTT2 style

Sure thing! i did not know this was ttt2 style, i was switching up several addons from ULX to the Server Addons Menu as ULX became more irrelevant. until know i didn't really knew the AddToSettingsMenu even existed :)

Tried it out and it seems working anyways, so i don't mind updating it

**Pull request merged**
